-- Migration: Create triangles table
-- Statistical loss development outputs generated by each Valuation
-- Typically three: paid, reported, incurred

CREATE TABLE triangles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    valuation_id UUID NOT NULL REFERENCES valuations(id) ON DELETE CASCADE,
    triangle_name VARCHAR(100) NOT NULL, -- UUID-like identifier for the triangle
    triangle_type VARCHAR(50) NOT NULL 
        CHECK (triangle_type IN ('paid', 'reported', 'incurred', 'case', 'ibnr', 'ultimate')),
    position VARCHAR(20) NOT NULL 
        CHECK (position IN ('left', 'center', 'right')),
    color VARCHAR(7), -- Hex color for visualization
    triangle_status VARCHAR(20) NOT NULL DEFAULT 'add'
        CHECK (triangle_status IN ('completed', 'add', 'pending-review', 'in_progress', 'error')),
    data_json JSONB, -- Triangle data structure (heatmap, growth_curve, mountain, age_to_age)
    development_factors JSONB, -- Store age-to-age factors
    ultimate_values JSONB, -- Store projected ultimate values
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX idx_triangles_valuation ON triangles(valuation_id);
CREATE INDEX idx_triangles_status ON triangles(triangle_status);
CREATE INDEX idx_triangles_type ON triangles(triangle_type);
CREATE INDEX idx_triangles_position ON triangles(position);

-- Unique constraint for position per valuation
ALTER TABLE triangles ADD CONSTRAINT unique_triangle_valuation_position 
    UNIQUE (valuation_id, position);

-- Insert sample triangles for completed valuations
INSERT INTO triangles (
    valuation_id,
    triangle_name,
    triangle_type,
    position,
    color,
    triangle_status,
    data_json,
    development_factors
) VALUES 
    -- Blue Commercial Auto Q4 2024 triangles
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Q4 2024 Year-End Valuation'),
        'cd12345e-6789-4abc-def0-123456789abc',
        'paid',
        'left',
        '#BD8B11',
        'completed',
        '{"heatmap": [[100, 150, 180], [120, 170, 200], [110, 160, 190]], "growth_curve": [{"x": 1, "y": 100}, {"x": 2, "y": 150}, {"x": 3, "y": 180}], "mountain": [{"age": 12, "value": 180}, {"age": 24, "value": 200}, {"age": 36, "value": 220}], "age_to_age": [1.5, 1.2, 1.1]}',
        '{"12_24": 1.50, "24_36": 1.20, "36_48": 1.10, "48_60": 1.05}'
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Q4 2024 Year-End Valuation'),
        'ab67890f-1234-5ghi-jkl6-789012345def',
        'incurred',
        'center',
        '#744DEB',
        'completed',
        '{"heatmap": [[120, 180, 220], [140, 200, 240], [130, 190, 230]], "growth_curve": [{"x": 1, "y": 120}, {"x": 2, "y": 180}, {"x": 3, "y": 220}], "mountain": [{"age": 12, "value": 220}, {"age": 24, "value": 240}, {"age": 36, "value": 260}], "age_to_age": [1.5, 1.22, 1.09]}',
        '{"12_24": 1.50, "24_36": 1.22, "36_48": 1.09, "48_60": 1.04}'
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Q4 2024 Year-End Valuation'),
        'ef34567g-5678-9mno-pqr0-345678901hij',
        'case',
        'right',
        '#3DA3CB',
        'completed',
        '{"heatmap": [[20, 30, 40], [24, 36, 44], [22, 34, 42]], "growth_curve": [{"x": 1, "y": 20}, {"x": 2, "y": 30}, {"x": 3, "y": 40}], "mountain": [{"age": 12, "value": 40}, {"age": 24, "value": 44}, {"age": 36, "value": 48}], "age_to_age": [1.5, 1.33, 1.2]}',
        '{"12_24": 1.50, "24_36": 1.33, "36_48": 1.20, "48_60": 1.10}'
    ),
    
    -- Red Workers Comp Year-End 2024 triangles (pending status - only basic setup)
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Year-End Assessment 2024'),
        'gh78901i-9012-3stu-vwx4-567890123klm',
        'paid',
        'left',
        '#BD8B11',
        'pending-review',
        NULL,
        NULL
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Year-End Assessment 2024'),
        'ij01234k-2345-6yza-bcd7-890123456nop',
        'incurred',
        'center',
        '#744DEB',
        'add',
        NULL,
        NULL
    ),
    
    -- Green Property Pre-Renewal Assessment triangles
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Pre-Renewal Assessment'),
        'kl45678m-6789-0efg-hij1-234567890qrs',
        'paid',
        'left',
        '#BD8B11',
        'completed',
        '{"heatmap": [[80, 120, 145], [85, 125, 150], [82, 122, 147]], "growth_curve": [{"x": 1, "y": 80}, {"x": 2, "y": 120}, {"x": 3, "y": 145}], "mountain": [{"age": 12, "value": 145}, {"age": 24, "value": 150}, {"age": 36, "value": 155}], "age_to_age": [1.5, 1.21, 1.07]}',
        '{"12_24": 1.50, "24_36": 1.21, "36_48": 1.07, "48_60": 1.03}'
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Pre-Renewal Assessment'),
        'mn89012o-0123-4klm-nop5-678901234tuv',
        'incurred',
        'center',
        '#744DEB',
        'completed',
        '{"heatmap": [[95, 140, 170], [100, 145, 175], [97, 142, 172]], "growth_curve": [{"x": 1, "y": 95}, {"x": 2, "y": 140}, {"x": 3, "y": 170}], "mountain": [{"age": 12, "value": 170}, {"age": 24, "value": 175}, {"age": 36, "value": 180}], "age_to_age": [1.47, 1.21, 1.06]}',
        '{"12_24": 1.47, "24_36": 1.21, "36_48": 1.06, "48_60": 1.03}'
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Pre-Renewal Assessment'),
        'op23456q-4567-8rst-uvw9-012345678xyz',
        'case',
        'right',
        '#3DA3CB',
        'add',
        NULL,
        NULL
    ),
    
    -- Purple Aviation Initial Performance Review triangles
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Initial Performance Review'),
        'qr67890s-8901-2abc-def3-456789012345',
        'paid',
        'left',
        '#BD8B11',
        'completed',
        '{"heatmap": [[60, 85, 95], [62, 87, 97], [61, 86, 96]], "growth_curve": [{"x": 1, "y": 60}, {"x": 2, "y": 85}, {"x": 3, "y": 95}], "mountain": [{"age": 12, "value": 95}, {"age": 24, "value": 97}, {"age": 36, "value": 100}], "age_to_age": [1.42, 1.12, 1.05]}',
        '{"12_24": 1.42, "24_36": 1.12, "36_48": 1.05, "48_60": 1.02}'
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Initial Performance Review'),
        'st01234u-2345-6ghi-jkl7-890123456789',
        'incurred',
        'center',
        '#744DEB',
        'completed',
        '{"heatmap": [[75, 105, 118], [77, 107, 120], [76, 106, 119]], "growth_curve": [{"x": 1, "y": 75}, {"x": 2, "y": 105}, {"x": 3, "y": 118}], "mountain": [{"age": 12, "value": 118}, {"age": 24, "value": 120}, {"age": 36, "value": 125}], "age_to_age": [1.40, 1.12, 1.06]}',
        '{"12_24": 1.40, "24_36": 1.12, "36_48": 1.06, "48_60": 1.04}'
    ),
    (
        (SELECT id FROM valuations WHERE valuation_name = 'Initial Performance Review'),
        'uv45678w-6789-0mno-pqr1-234567890123',
        'case',
        'right',
        '#3DA3CB',
        'completed',
        '{"heatmap": [[15, 20, 23], [16, 21, 24], [15.5, 20.5, 23.5]], "growth_curve": [{"x": 1, "y": 15}, {"x": 2, "y": 20}, {"x": 3, "y": 23}], "mountain": [{"age": 12, "value": 23}, {"age": 24, "value": 24}, {"age": 36, "value": 25}], "age_to_age": [1.33, 1.15, 1.09]}',
        '{"12_24": 1.33, "24_36": 1.15, "36_48": 1.09, "48_60": 1.04}'
    );